version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "secrets-manager-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u3oxmmrhwosp"
s3_prefix = "secrets-manager-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SecretName=\"mynames\""
image_repositories = []
